version: "3.8"
services:
    hss-solver:
        build: .
        environment:
            - VIRTUAL_HOST=hss.aidandev.ca,hss.engscitools.ca
        # ports:
        #     - "5000:80"
        restart: unless-stopped
        network_mode: "bridge"